name: Rust

on:
    push:
    pull_request:

jobs:
    rust:
        uses: FyraLabs/actions/.github/workflows/rust.yml@main
        with:
            test-container: '{"image": "ghcr.io/terrapkg/builder:f42"}'
            test-pre: dnf install -y clang-devel gcc mold cmake pkg-config libevdev-devel libudev-devel dbus-devel